add_external_project(netcdf4
  DEPENDS hdf5 zlib szip
  BUILD_IN_SOURCE 0
  PATCH_COMMAND
    "${CMAKE_COMMAND}"
      "-DPATCHES_DIR:PATH=${SuperBuild_PROJECTS_DIR}/patches/"
      "-DSOURCE_DIR:PATH=<SOURCE_DIR>"
      "-DINSTALL_DIR:PATH=<INSTALL_DIR>"
      -P "${SuperBuild_PROJECTS_DIR}/netcdf4.patch.cmake"
  CMAKE_ARGS
    -DENABLE_NETCDF_4:BOOL=TRUE
    -DHDF5_DIR:PATH=<INSTALL_DIR>
    -DBUILD_SHARED_LIBS:BOOL=TRUE
    -DBUILD_V2:BOOL=TRUE
    -DENABLE_DAP:BOOL=FALSE
 )
